---
- hosts: localhost
  connection: local 
  become: true

    
  tasks:

  - name: install packages
    package: 
      name: 
        - htop
  ### Installing multiple packages
  #       - tmux
  #       - rustup
  #

  ## testing running scripts 
  - name:  run bash scripts
    ansible.builtin.script:
      cmd: echo " testing "
      
  
