---
- name: Install nvm
  hosts: localhost
  vars_files:
    - ../../var/source.yml
  vars:
    nvm_tags: ["node", "nvm", "npm"]
  tasks:
    - name: Check if NVM is installed
      shell: "{{source_bash}} && command -v nvm"
      register: nvm_exists
      ignore_errors: yes
      tags: "{{ nvm_tags }}"

    - name: Download Installer
      when: nvm_exists is failed
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh
        dest: /tmp/sh.nvm.sh
        mode: "0755"
        force: "yes"
      tags: "{{ nvm_tags }}"

    - name: Install nvm
      when: nvm_exists is failed
      ansible.builtin.shell: >
        . /tmp/sh.nvm.sh
      args:
        executable: /bin/bash
      tags: "{{ nvm_tags }}"

    - name: Install Node.js using nvm
      shell: "{{ source_nvm }} && nvm install node && nvm use node"
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
        chdir: "{{ ansible_env.HOME }}"
        executable: /bin/bash

    - name: Add nvm to path ⏯️
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "{{ source_nvm }}"
      tags: "{{ nvm_tags }}"
