- hosts: "localhost"
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: true
        upgrade: "yes"

    - name: Install Build tools
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - "build-essential"
        - "make"
        - "ripgrep"
        - "fzf"
        - "tmux"
        - "xclip"
        - "tldr"
        - "python3"
        - "pass"
        - "exa"
