- hosts: "localhost"
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: true
        upgrade: "yes"

    - name: Install Build tools
      apt:
        pkg:
          - "build-essential"
          - "make"
