- hosts: "localhost"
  become: yes
  name: Cargo installations
  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes

    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: "yes"
      tags:
        - rust

    - name: Install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: check if bob-nvim is installed
      shell: command -v bob
      register: bob_exists
      ignore_errors: yes

    - name: Install bob-nvim
      when: bob_exists is failed
      shell: cargo install bob-nvim
      tags:
        - bob-nvim

    - name: Add bob nvim bins to path
      shell: export PATH=$PATH:$HOME/.local/share/bob/nvim-bin/
